---
# robertdebock.httpd
httpd_vhosts:
  - name: mediawiki
    template: mediawiki
    servername: localhost
    documentroot: /var/www/localhost/mediawiki

# robertdebock.mysql
mysql_root_password: mysql

# robertdebock.mediawiki
mediawiki_destination: /var/www/localhost/mediawiki
mediawiki_name: openresearch        # "technical" name

mediawiki_wiki_name: Openresearch   # (optional) wiki name, $wgSitename
mediawiki_admin_name: Admin
mediawiki_admin_password: wiki4everyone
mediawiki_database_password: openresearch
mediawiki_server: http:\\localhost:8080

mediawiki_custom_source: "/vagrant/_custom"
mediawiki_custom_destination: "{{ mediawiki_destination }}/wiki-{{ mediawiki_name }}"