name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ansible check with debian:buster

        uses: roles-ansible/check-ansible-debian-buster-action@master
        with:
          targets: "./ansible/playbook.yml"
          group: "local"
          hosts: "localhost"
          requirements: "./ansible/requirements.yml"
