name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    ## "Service is in unknown state" issue
    ## https://github.com/ansible/ansible/issues/71528
    ## ubuntu-latest: Linux 5.11.0-1021-azure #22~20.04.1-Ubuntu SMP Fri Oct 29 01:11:25 UTC 2021
    ## ubuntu-18-04:  Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: ansible check with debian:bullseye

        uses: roles-ansible/check-ansible-debian-bullseye-action@main
        with:
          targets: "./ansible/playbook.yml"
          group: "local"
          hosts: "localhost"
          requirements: "./ansible/requirements.yml"
