name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    ## "Service is in unknown state" issue
    ## https://github.com/ansible/ansible/issues/71528
    ## ubuntu-latest: Linux 5.11.0-1021-azure #22~20.04.1-Ubuntu SMP Fri Oct 29 01:11:25 UTC 2021

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: ansible check with debian:buster

        uses: alexander-gesinn/check-ansible-debian-buster-action@master
        with:
          targets: "./ansible/playbook.yml"
          group: "local"
          hosts: "localhost"
          requirements: "./ansible/requirements.yml"
